name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-all-apps:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CodeItHere/CodeItHere.sln
    - name: Build
      run: dotnet build CodeItHere/CodeItHere.sln --no-restore
    - name: Test
      run: dotnet test CodeItHere/CodeItHere.sln --no-build --verbosity normal
